### PR TITLE
CI: move from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by Minoru**
This successfully built in my fork:
- Linux: https://github.com/Minoru/gettext-rs/actions/runs/401489252
- macOS: https://github.com/Minoru/gettext-rs/actions/runs/401489251

### CODE REVIEW

**Review by Koka — APPROVED** [review]

**Comment by Minoru** [comment]
I can't merge despite the approval :( I'll go merge into master directly.

**Comment by Minoru** [comment]
Yeah, that doesn't work as well:

```
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 8 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (15/15), 2.98 KiB | 761.00 KiB/s, done.
Total 15 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Travis CI - Pull Request" is expected.
To github.com:Koka/gettext-rs.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:Koka/gettext-rs.git'
```

@Koka, please merge this manually.

**Comment by Koka** [comment]
Done

**Comment by Minoru** [comment]
Thanks! The builds are green now, yay ^_^

**Comment by Koka** [comment]
I also removed travis checks from master branch protection and added GitHub actions checks instead

**Pull request merged**
