### PR TITLE
Use newer macOS on Travis

### PR DESCRIPTION
**Pull request by Minoru**
This should fix Homebrew warnings about old Xcode.

### CODE REVIEW

**Comment by Minoru** [comment]
@Koka It appears that this PR fixes the macOS failure experienced by #27, but Travis still won't report the branch status. Apparently you'll have to [tweak some settings](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154) to fix that (I can't do this because I'm not the owner of the repo).

**Comment by Minoru** [comment]
Meanwhile, I'll see if I can migrate Travis jobs to GitHub Actions. Travis really made me sad with their limiting the capacity for FLOSS projects.

**Comment by Koka** [comment]
I really thought I've applied Travis changes you mentioned 🤔

**Review by Koka — APPROVED** [review]

**Comment by Koka** [comment]
Btw I can see green travis status in this PR

**Comment by Minoru** [comment]
Here's how it looks to me:
Screenshot_2020-12-04 Use newer macOS on Travis by Minoru · Pull Request #28 · Koka gettext-rs

The branch build [passed successfully](https://travis-ci.com/github/Minoru/gettext-rs/builds/206392867), but GitHub didn't get a notification about that, and thus doesn't let me merge the PR through the UI :(

Anyway, let's keep this open for now while I'm investigating GitHub Actions. If my attempt at it fails, I'll merge this PR via the command line.

**Comment by Koka** [comment]
Not sure why it's so, but I have disabled "Branch" check and leave only "Pull Request" as mandatory, so this PR is mergeable now

**Comment by Minoru** [comment]
Weird: even with that, I still won't be able to merge:

Screenshot_2020-12-04 Use newer macOS on Travis by Minoru · Pull Request #28 · Koka gettext-rs(1)

**Comment by Koka** [comment]
Now it just saying your fork is outdated and is behind master

**Comment by Minoru** [comment]
Hm, I don't think that's what was blocking it, but let's check.

**Comment by Minoru** [comment]
Superseded by #30.

**Pull request closed without merging**
