### PR TITLE
Draft: MSVC support

### PR DESCRIPTION
**Pull request by nacho**
Set of commits that allows the library to build using msvc

### CODE REVIEW

**Comment by Minoru** [comment]
Thank you! The CI here failed because of GNU-vs-BSD differences in `tar`, see #81 for the entire story. We intend to replace the tarball with a Git submodule (see #81 again), but nobody did the work yet. If you're itching to get this merged, it's probably best to do the submodule first, and then the Windows build would be easier.

**Comment by nacho** [comment]
My idea was actually that the library would be given from outside, i.e using gvsbuild like in this commit or maybe using vcpkg.

**Comment by nacho** [comment]
@Minoru I've found out that there was already a way to pass the gettext binaries with GETTEXT_BIN_DIR, GETTEXT_LIB_DIR and GETTEXT_INCLUDE_DIR.

So now it builds but the tests are not passing due some mistake in the code

**Comment by nacho** [comment]
Dropping this for now to avoid so much spam

**Pull request closed without merging**
