### PR TITLE
Add CI for Windows & fix tar issue on Windows

### LINKED ISSUE #12: Can not build gettext-sys on windows
error: failed to run custom build command for `gettext-sys v0.19.8 (N:\gettext-rs\gettext-sys)`
process didn't exit successfully: `N:\gettext-rs\target\debug\build\gettext-sys-70cac4af73bac902\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_GETTEXT_SYSTEM
cargo:rerun-if-env-changed=GETTEXT_SYSTEM
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_GETTEXT_DIR
cargo:rerun-if-env-changed=GETTEXT_DIR
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_GETTEXT_BIN_DIR
cargo:rerun-if-env-changed=GETTEXT_BIN_DIR
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_GETTEXT_LIB_DIR
cargo:rerun-if-env-changed=GETTEXT_LIB_DIR
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_GETTEXT_INCLUDE_DIR
cargo:rerun-if-env-changed=GETTEXT_INCLUDE_DIR
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
DEBUG = Some("true")
running: "tar" "xJf" "N:\\gettext-rs\\gettext-sys\\gettext-0.19.8.1.tar.xz" "--strip-components" "1" "--force-local"

--- stderr
tar: Option --force-local is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', gettext-sys\build.rs:251:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

### PR DESCRIPTION
**Pull request by cecton**
Fixes #12

### CODE REVIEW

**Comment by cecton** [comment]
@Minoru pardon my ignorance but I have a maybe stupid question: gettext-sys is only buildable in a GNU environment on Windows? It is impossible to compile on MSVC?

**Comment by cecton** [comment]
@Minoru ok I think the specific issue with the tar command in #12 is fixed here. I added CI for the windows build and replaced a few functions by macros to improve the line number in the stack traces.

I'm now getting this error (only on GitHub, I have not tested locally) which I don't know how to fix:

```
[...]

  running: "make" "-j2"

  --- stderr
  configure: WARNING: libacl development library was not found or not usable.
  configure: WARNING: gettext-tools will be built without ACL support.
  mingw32-make: *** No rule to make target '/C/Users/RUNNER~1/AppData/Local/Temp/t17e8-0/gettext/Makefile.am', needed by '/C/Users/RUNNER~1/AppData/Local/Temp/t17e8-0/gettext/Makefile.in'.  Stop.
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', gettext-sys\build.rs:290:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And the builds on MSVC don't work for some other reason.

**Comment by Minoru** [comment]
> pardon my ignorance but I have a maybe stupid question

Please don't be so hard on yourself ;) And thanks for working on this!

> gettext-sys is only buildable in a GNU environment on Windows? It is impossible to compile on MSVC?

I only ever tried to build it with MinGW, but [upstream has docs](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=INSTALL.windows;h=72efd29f269ef0b83d777d873eb744c589c0cde9;hb=eb83efc3b58d690d444da0b82c3ecf36a54f28ac) for building with MSVC and also Cygwin. I haven't read them attentively yet, not sure how relevant they are.

> I'm now getting this error (only on GitHub, I have not tested locally)

I tried this PR on Debian and I'm not getting this error; don't have a Windows machine to test on. I also have no idea how Makefile.am could go missing. Perhaps try running `ls -lR gettext` to see how the unpacked tree looks like?

Alternative idea: roll back to `master`, drop `--force-local` option, and concentrate on Windows CI. Once Windows CI is green, proceed to solving the `tar` problem.

<hr>

Overall:
1. I like the idea with macros, and I'd merge it even without the rest of these changes;
2. I'm not sure that depending on `tar` and `xz` is a good idea. They pull in a lot more crates (14 vs. 2) and increase the compile time noticeably (3 seconds vs 1.5s on `master` on my machine). It doesn't sound like a big deal, and it's not for *our* CI, but the end users will notice.

    If you want, you may concentrate on Windows CI, and once you got it running, I can take over and try out my "run `tar` twice" idea. If that fails, we can roll back to `tar` and `xz` crates. How does that sound?

**Comment by cecton** [comment]
> 2\. If you want, you may concentrate on Windows CI, and once you got it running, I can take over and try out my "run `tar` twice" idea. If that fails, we can roll back to `tar` and `xz` crates. How does that sound?

tbh I think it's terrible :sweat_smile: I think it's better to have one common and consistent way to do things if the goal is to be portable/compatible. Imagine tomorrow there is a new OS and again new particularities.

Also, imo, it doesn't look bad to the point of making improvements and sacrifying the portability/compatibility:

```
gettext-sys v0.21.2 (/home/cecile/repos/gettext-rs/gettext-sys)
[build-dependencies]
├── cc v1.0.69
├── tar v0.4.35
│   ├── filetime v0.2.14
│   │   ├── cfg-if v1.0.0
│   │   └── libc v0.2.98
│   ├── libc v0.2.98
│   └── xattr v0.2.2
│       └── libc v0.2.98
├── temp-dir v0.1.11
└── xz2 v0.1.6
    └── lzma-sys v0.1.17
        └── libc v0.2.98
        [build-dependencies]
        ├── cc v1.0.69
        └── pkg-config v0.3.19
```
(xattr is optional and I think could be removed)

That being said. I'm not owner and it's not my call. Swapping arguments works too and is fine.

One alternative would be to do like lzma-sys does: to include the sources of gettext as a submodules in the project: https://github.com/alexcrichton/xz2-rs/tree/master/lzma-sys

**Comment by marin-m** [comment]
> I think it's better to have one common and consistent way to do things if the goal is to be portable/compatible.

Agreed. Rust is a language that has many modern features such as memory safety or borrow checking, or some OO concepts. Having critical modules taking the stance of randomly not being multi-platform while being widespread and standard is taking the choice of losing something that we had commonly accepted since the 80's.

>I'm not sure that depending on `tar` and `xz` is a good idea. They pull in a lot more crates (14 vs. 2) and increase the compile time noticeably (3 seconds vs 1.5s on master on my machine).

Waiting one second and half is a non-thing to worry when just building the crate. It's non-substantial.

Doing Rust implies to accept cascades of dependencies, and almost always waiting a lot more than 3 seconds when first building a project with various dependency crates. It's due to the way the ecosystem is built, as a fractioned community effort rather than an attempt to produce a large unified standard package like the Python or Boost communities have. These few minutes of waiting during the first build are seldom a too significant fraction of the life of the concerned users anyway.

Also, having non-building crates has a lot more impact over the perception of the user over the library than having to cope with a one-time ≃ 1.5 sec wait.

Regarding the size of the dependency tree, as I mentioned above I'm not sure that this is really a concern, but you may first possibly want to drop the `xz` compression layer if this allows to have one less dependencies. (If over-optimization is really wanted, you may seek for a differently dependent crate that also accomplishes the task or possibly write your own, but the dependencies here look quite honest - I'm not counting 14 crates since `libc` is present multiple times for example.)

As a reminder, Cargo allows not only to specify build time-only dependencies, but also allows to fetch and use the concerned crates only against certain platforms: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#build-dependencies

Regards,

**Comment by cecton** [comment]
Actually I just realized afterward that the XZ file is versioned inside this repository. I thought it was downloaded. So you could change the compression format if you want.

I also noticed that the tar.xz file comes with a `configure` script but according to the INSTALL of the repo, this configure is not supposed to be distributed but generated by autoconf. I tried to do it on my machine but autoconf fails with a lot of warnings. I noticed also there is a submodule to another repo.

**Comment by Minoru** [comment]
Sorry, I went on a break without telling anyone. But I'm back now, let's figure this out :)

The proposals so far are:

1. include GNU gettext as a submodule, which lets us drop tar.xz and nullify this entire problem;
2. use a different compression algorithm (which lets us drop the `xz` crate);
3. use `tar`+`xz` crates on all platforms;
4. try invoking `tar` executable with different options to see which one succeeds;
5. use `tar` executable where we can and fall back to `tar`+`xz` crates elsewhere using Cargo's "platform-specific dependencies" feature.

Option 1 is my preference. However, .crate files are compressed with gzip, and the result is 23MB. [crates.io limits crates to 10MB](https://doc.rust-lang.org/cargo/reference/publishing.html), but [we can request an increase](https://github.com/rust-lang/crates.io/issues/3649#issuecomment-848564703). I'll do that once I posted this comment.

In case that doesn't pan out, let me comment on the other options as well.

Option 2 doesn't address the core of my complaints; we'd still depend on more crates than I wish.

Option 3 is indeed the most portable, but I still doubt that we need to compile our own versions of everything. The user needs a Unix-y environment to compile GNU gettext anyway, so they'll probably have `tar` already. `xz` might still pose a problem on older/insular platforms though. Either way, I don't feel it's right to compile something that the user already has.

Option 4 is kind of an opposite of Option 3. As you correctly point out, it's less portable and it's prone to break on new platforms.

Option 5 is a compromise between Options 3 and 4, and it would be my preference if Option 1 falls through. It can still break if a platform is configured weirdly (e.g. user uninstalled `tar` from Linux, where we'd expect `tar` to always exist), but that's on the user :P I also don't see how we'd test it (we need a platform that doesn't have `tar` out of the box, but all of the ones that are available in public CI services have `tar`).

There's also an option to trim down the tarball; I don't think we need gettext-tools, for example. The problem with this approach is that we have to change Autotools configs as well, because it mentions the files we'd like to delete. This is far more work than I'd like to take on, so I don't really consider this unless someone wants to do the work.

@cecton

> I also noticed that the tar.xz file comes with a configure script but according to the INSTALL of the repo, this configure is not supposed to be distributed but generated by autoconf

Can you quote the part of INSTALL that states this? I don't see that in https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=INSTALL;h=671b157a6429121883c370dbfd80f4b09217cb26;hb=HEAD As far as I understand, it's customary to ship `configure` script, so users don't have to run Autoconf themselves.

> I tried to do it on my machine but autoconf fails with a lot of warnings.

Yeah, they require a very recent autoconf, see https://github.com/Koka/gettext-rs/issues/76#issuecomment-895352184.

**Comment by cecton** [comment]
> Can you quote the part of INSTALL that states this? I don't see that in https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=INSTALL;h=671b157a6429121883c370dbfd80f4b09217cb26;hb=HEAD As far as I understand, it's customary to ship `configure` script, so users don't have to run Autoconf themselves.

I can't find it. I think I probably just misinterpreted what it says.

> Option 1 is my preference. However, .crate files are compressed with gzip, and the result is 23MB. [crates.io limits crates to 10MB](https://doc.rust-lang.org/cargo/reference/publishing.html), but [we can request an increase](https://github.com/rust-lang/crates.io/issues/3649#issuecomment-848564703). I emailed [help@crates.io](mailto:help@crates.io) asking them to raise the limit for gettext-sys to 25MB.

Is it possible to exclude part of the submodule being uploaded to crates.io using [`include`/`exclude` from Cargo.toml](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields)? Probably this would impact also the autotools config?

> Option 5 is a compromise between Options 3 and 4, and it would be my preference if Option 1 falls through. It can still break if a platform is configured weirdly (e.g. user uninstalled `tar` from Linux, where we'd expect `tar` to always exist), but that's on the user :P I also don't see how we'd test it (we need a platform that doesn't have `tar` out of the box, but all of the ones that are available in public CI services have `tar`).

The problem is mostly due to the different versions of tar. Maybe there is a way to shift part of the work to the `build.rs` and use only std::fs's functions.

> There's also an option to trim down the tarball; I don't think we need gettext-tools, for example. The problem with this approach is that we have to change Autotools configs as well, because it mentions the files we'd like to delete. This is far more work than I'd like to take on, so I don't really consider this unless someone wants to do the work.

I don't have enough time for that and it sounds difficult to maintain. I don't know much about the C build tools but I can smell a big pitfall here haha :laughing: 

> they'll probably have `tar` already. `xz` might still pose a problem on older/insular platforms though.

I do think it's best to use gzip if the size wouldn't be that much of a problem. gzip is more portable. xz is not a huge deal though. It's maybe not worth giving too much effort on it.

> Option 1 is my preference. However, .crate files are compressed with gzip, and the result is 23MB. [crates.io limits crates to 10MB](https://doc.rust-lang.org/cargo/reference/publishing.html), but [we can request an increase](https://github.com/rust-lang/crates.io/issues/3649#issuecomment-848564703). I emailed [help@crates.io](mailto:help@crates.io) asking them to raise the limit for gettext-sys to 25MB.

I think we should wait for a feedback on this before doing anymore effort on this. It really is the best and simplest option.

**Comment by marin-m** [comment]
> There's also an option to trim down the tarball; I don't think we need gettext-tools, for example. The problem with this approach is that we have to change Autotools configs as well, because it mentions the files we'd like to delete.

Indeed, I think that we don't need *all* the Gettext source to be included in the tree. I see that the `gettext-tools` folder alone is 92 MB uncompressed and the `libtextstyle/lib/libxml` folder alone is 6.3 MB uncompressed, for example. And `libxml` is an example of explicitly external dependency that's included in the source package:

```c
/* libxml2 - Library for parsing XML documents
 * Copyright (C) 2006-2019 Free Software Foundation, Inc.
 *
 * This file is not part of the GNU gettext program, but is used with
 * GNU gettext.
```

Regarding `gettext-tools`, I think that the Automake input files (`Makefile.am` and `configure.ac`) could be changed with just a few `sed` commands and re-running the `Makefile.in`/`Makefile`/`configure` generation commands, as there are not much occurrences of `gettext-tools` in the root files: in `Makefile.am`, a lot of occurrences are constructed on the same patterns (and should then be able to be processed with the same `sed` commands) and in `configure.ac` there are just three occurrences.

See:

```bash
grep gettext-tools Makefile.am
grep gettext-tools configure.ac
```

And then, the auto-Automake files rewriting script could be bundled in the repository and executing before the modified source is pushed to Git/whenever we change the copied GNU Gettext source tree version.

Anyway avoiding to do XZ-in-GZip compression is sane.

> crates.io limits crates to 10MB, but we can request an increase. I emailed help@crates.io asking them to raise the limit for gettext-sys to 25MB.

Maybe than even asking for 50 MB is reasonable...

> I can't find it. I think I probably just misinterpreted what it says.

IMHO, in the case where first trying to run `autogen.sh`/`automake` before `configure` resolves the issues of still majorly used distribution (supported Ubuntu LTS) not being able to build in certain conditions, it may be worth it and more clean to try to run Automake beforehand (possibly fallbacking on the built-in `configure` if it doesn't work). It was objected that it may be an issue at `automake` could try to connect to the Internet in certain cases (maybe that it can be configured if it is the case?), but:
* As if I understood the library should be changed by dynamic linking by default, as it is saner, it should not be a problem
* The consequences of Automake being being tried to run would still represent less effort in all cases for the users than having the library not building
* Falling back on using the existing `configure` if Automake is not available is still possible in all cases

>include GNU gettext as a submodule, which lets us drop tar.xz and nullify this entire problem;

Maybe that directly including in the source tree as a subfolder rather than a submodule is better. People forget to put the `--recursive` or other akin flag when cloning all the time.

**Comment by cecton** [comment]
> Maybe that directly including in the source tree as a subfolder rather than a submodule is better. People forget to put the `--recursive` or other akin flag when cloning all the time.

That actually is not a problem. When publishing the crate, the submodule is not there, I don't think the .git is even included. Only the sources. It won't be a problem.

If people use the repo in their dependency it will work normally too because cargo already clone the submodules properly.

No worry at all there.

**Comment by Minoru** [comment]
Yay, the limit was raised on crates.io! @cecton, would you replace the tar.xz with a submodule in this PR please?

**Comment by cecton** [comment]
> Yay, the limit was raised on crates.io! @cecton, would you replace the tar.xz with a submodule in this PR please?

sure! I'll give it a try this weekend hopefully

**Comment by hboetes** [comment]
I think my failed attempt to build https://github.com/marin-m/SongRec/ on OpenBSD depends on this ticket, so let's subscribe.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Hello
Any plans on continuation about this? I wish if I can do it my self but I have no idea about what to do.

**Comment by cecton** [comment]
It looks like I said I would do something and then I forgot :sweat:

**Comment by theCapypara** [comment]
Hi! Just chiming in here to give some motivation, I would love to see this finished since I really need the lib working on Windows as well and the tar issue is a bit of a pain to work around in CI builds :)

**Comment by cecton** [comment]
@theCapypara to be honest I'm really incapable to do this at the moment. I'm a bit burned out. So feel free to fork or push on this branch (I allowed modifications on it or I can add you to my fork).

I think the main issue is actually to agree on a good solution.

**Comment by Minoru** [comment]
I also don't have the energy to actually work on this right now, but I'm around to review any PRs that might come. (Thanks for the work you've already done here, @cecton!)

> So feel free to fork or push on this branch (I allowed modifications on it or I can add you to my fork).

I'd prefer a separate PR, it's just easier for everybody. Actually, I'll just close this PR so it doesn't dissuade others from submitting their own :) I'll also post a recap on #12.

> I think the main issue is actually to agree on a good solution.

I believe we've found the solution for the tar problem, which is: replace the tarball with a Git submodule. Once that's done, I think the Windows CI would be straightforward to implement.

**Comment by dabrain34** [comment]
thread 'main' panicked at 'failed to excute process: Error { kind: NotFound, message: "program not found" }', C:\Users\toto\.cargo\registry\src\github.com-1ecc6299db9ec823\gettext-sys-0.21.3\build.rs:69:14

I'm getting this error when I'm building in a powershell.

**Pull request closed without merging**
